import Nav from "@/components/Nav";
import Providers from "@/components/Providers";
import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <Sidebar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
