import Nav from "@/components/Nav";
<<<<<<< Updated upstream
=======
import Providers from "@/components/Providers";
import Sidebar from "@/components/Sidebar";
>>>>>>> Stashed changes

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// const fetcher = async (uri: string) => {
//   const resp = await fetch(uri);
//   if (resp.ok) {
//     return await resp.json();
//   }
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
<<<<<<< Updated upstream
        <Nav/>
          {children}
=======
        <Nav />
        <Sidebar />
        <Providers>{children}</Providers>
>>>>>>> Stashed changes
      </body>
    </html>
  );
}
