import { SWRConfig } from "swr";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const fetcher = async (uri: string) => {
  const resp = await fetch(uri);
  if (resp.ok) {
    return await resp.json();
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SWRConfig value={{ fetcher: fetcher }}>
          {children}
        </SWRConfig>
      </body>
    </html>
  );
}
