import Communities from "@/components/Communities";
import Nav from "@/components/Nav";
import Providers from "@/components/Providers";
import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
// todo refactor to move context deeper in the tree
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </head>
      <body>
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
