"""empty message

Revision ID: fe6c639df362
Revises: 4b1eb39793b9
Create Date: 2023-07-11 11:57:46.483026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6c639df362'
down_revision = '4b1eb39793b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('_password_digest',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('_password_digest',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
