"""empty message

Revision ID: 65bfcb035834
Revises: a0a55b6a1861
Create Date: 2023-07-16 20:11:27.674032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65bfcb035834'
down_revision = 'a0a55b6a1861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved', sa.Boolean(), nullable=True))
        batch_op.drop_column('save')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('save', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('saved')

    # ### end Alembic commands ###
